import { createAssessmentCinemaSeatMap, flattenSeats } from "./cinema-layout";
import type { SeatMap, SeatState } from "./types";

export const DEFAULT_BROKEN_SEATS = [
  "C7",
  "E3",
  "E24",
  "J25",
  "L12",
  "M15",
  "M23",
] as const;

export const SCENARIO_IDS = [
  "empty",
  "halfFull",
  "nearlyFull",
  "orphanRisk",
  "soloRisk",
  "vipAccessibleRisk",
  "adminOverrideDemo",
] as const;

export type ScenarioId = (typeof SCENARIO_IDS)[number];

export interface SeatingScenario {
  id: ScenarioId;
  name: string;
  purpose: string;
  seatMap: SeatMap;
}

type ScenarioStatePlan = Partial<Record<SeatState, readonly string[]>>;

const SCENARIO_DEFINITIONS: Record<
  ScenarioId,
  {
    name: string;
    purpose: string;
    statePlan: ScenarioStatePlan;
  }
> = {
  empty: {
    name: "Empty",
    purpose: "All defined seats start available, with zones preserved.",
    statePlan: {},
  },
  halfFull: {
    name: "Half-full",
    purpose: "Moderate occupancy with deterministic broken seats.",
    statePlan: {
      booked: [
        "A5",
        "A6",
        "A7",
        "A18",
        "A19",
        "B1",
        "B2",
        "B3",
        "B20",
        "B21",
        "B22",
        "C1",
        "C2",
        "C15",
        "C16",
        "D5",
        "D6",
        "D7",
        "D8",
        "E10",
        "E11",
        "F2",
        "F3",
        "F20",
        "F21",
        "G7",
        "G8",
        "G9",
        "H10",
        "H11",
        "I18",
        "I19",
        "J10",
        "J11",
        "K22",
        "K23",
        "L7",
        "L8",
        "M20",
        "M21",
        "N21",
        "N22",
        "O24",
        "O25",
      ],
      held: ["D22", "D23", "G24"],
      broken: DEFAULT_BROKEN_SEATS,
    },
  },
  nearlyFull: {
    name: "Nearly full",
    purpose: "Stress case with only a few legal contiguous blocks remaining.",
    statePlan: {
      booked: [
        "A1",
        "A2",
        "A5",
        "A6",
        "A7",
        "A8",
        "A9",
        "A10",
        "A11",
        "A12",
        "A13",
        "A14",
        "A15",
        "A16",
        "A17",
        "A18",
        "A19",
        "A20",
        "A21",
        "A22",
        "A23",
        "A24",
        "A27",
        "A28",
        "B1",
        "B2",
        "B3",
        "B4",
        "B5",
        "B6",
        "B7",
        "B8",
        "B9",
        "B10",
        "B11",
        "B12",
        "B16",
        "B17",
        "B18",
        "B19",
        "B20",
        "B21",
        "B22",
        "B23",
        "B24",
        "B25",
        "B26",
        "B27",
        "B28",
        "C1",
        "C2",
        "C3",
        "C4",
        "C5",
        "C6",
        "C8",
        "C9",
        "C10",
        "C11",
        "C12",
        "C13",
        "C14",
        "C15",
        "C16",
        "C17",
        "C18",
        "C19",
        "C20",
        "C21",
        "C22",
        "C23",
        "C24",
        "C25",
        "C26",
        "C27",
        "C28",
        "D1",
        "D2",
        "D3",
        "D4",
        "D5",
        "D6",
        "D7",
        "D8",
        "D9",
        "D10",
        "D11",
        "D12",
        "D13",
        "D14",
        "D15",
        "D16",
        "D17",
        "D18",
        "D19",
        "D20",
        "D21",
        "D22",
        "D23",
        "D24",
        "D25",
        "D26",
        "D27",
        "D28",
        "E1",
        "E2",
        "E4",
        "E5",
        "E6",
        "E7",
        "E8",
        "E9",
        "E10",
        "E11",
        "E12",
        "E13",
        "E14",
        "E15",
        "E16",
        "E17",
        "E18",
        "E19",
        "E20",
        "E21",
        "E22",
        "E23",
        "E25",
        "E26",
        "E27",
        "E28",
        "F2",
        "F3",
        "F4",
        "F5",
        "F6",
        "F7",
        "F8",
        "F9",
        "F10",
        "F11",
        "F12",
        "F13",
        "F14",
        "F15",
        "F16",
        "F17",
        "F18",
        "F19",
        "F20",
        "F21",
        "F22",
        "F23",
        "F24",
        "F25",
        "F26",
        "F27",
        "F28",
        "G3",
        "G4",
        "G5",
        "G6",
        "G7",
        "G8",
        "G9",
        "G10",
        "G11",
        "G12",
        "G13",
        "G14",
        "G15",
        "G16",
        "G17",
        "G18",
        "G19",
        "G20",
        "G21",
        "G22",
        "G23",
        "G24",
        "G25",
        "G26",
        "G27",
        "H4",
        "H5",
        "H6",
        "H7",
        "H8",
        "H9",
        "H10",
        "H11",
        "H12",
        "H13",
        "H14",
        "H15",
        "H16",
        "H17",
        "H18",
        "H19",
        "H20",
        "H21",
        "H22",
        "H23",
        "H24",
        "H25",
        "H26",
        "I5",
        "I6",
        "I7",
        "I8",
        "I9",
        "I10",
        "I11",
        "I12",
        "I13",
        "I14",
        "I15",
        "I16",
        "I17",
        "I18",
        "I19",
        "I20",
        "I21",
        "I22",
        "I23",
        "I24",
        "I25",
      ],
      held: ["J6", "J7", "J8", "J9", "K6", "K7", "K8", "K9"],
      broken: DEFAULT_BROKEN_SEATS,
    },
  },
  orphanRisk: {
    name: "Orphan risk",
    purpose:
      "Creates competing choices where one choice would leave a single seat.",
    statePlan: {
      booked: [
        "G3",
        "G4",
        "G9",
        "G10",
        "H4",
        "H5",
        "H6",
        "H11",
        "H12",
        "I5",
        "I6",
        "I11",
        "I12",
        "J6",
        "J7",
        "J12",
        "J13",
      ],
      broken: DEFAULT_BROKEN_SEATS,
    },
  },
  soloRisk: {
    name: "Solo risk",
    purpose: "Tests safe solo placement around occupied clusters.",
    statePlan: {
      booked: [
        "K10",
        "K11",
        "K13",
        "K14",
        "K22",
        "K23",
        "L13",
        "L14",
        "L16",
        "L17",
      ],
      broken: DEFAULT_BROKEN_SEATS,
    },
  },
  vipAccessibleRisk: {
    name: "VIP/accessibility risk",
    purpose:
      "Ensures restricted zones are visible and reserved by request type.",
    statePlan: {
      booked: [
        "E10",
        "E11",
        "E16",
        "E17",
        "F10",
        "F11",
        "F16",
        "F17",
        "N7",
        "N8",
        "O7",
        "O8",
      ],
      held: ["N21", "N22"],
      broken: DEFAULT_BROKEN_SEATS,
    },
  },
  adminOverrideDemo: {
    name: "Admin override demo",
    purpose: "Presents restricted and broken seats for override demonstration.",
    statePlan: {
      booked: ["E12", "E13", "E14", "N5", "N6", "O19", "O20"],
      unavailable: ["B12", "B13", "B14"],
      broken: DEFAULT_BROKEN_SEATS,
    },
  },
};

export function createScenario(scenarioId: ScenarioId): SeatingScenario {
  const definition = SCENARIO_DEFINITIONS[scenarioId];

  return {
    id: scenarioId,
    name: definition.name,
    purpose: definition.purpose,
    seatMap: applyStatePlan(
      createAssessmentCinemaSeatMap(),
      definition.statePlan
    ),
  };
}

export function createScenarioSeatMap(scenarioId: ScenarioId): SeatMap {
  return createScenario(scenarioId).seatMap;
}

function applyStatePlan(seatMap: SeatMap, statePlan: ScenarioStatePlan) {
  const stateBySeatId = new Map<string, SeatState>();

  for (const [state, seatIds] of Object.entries(statePlan) as [
    SeatState,
    readonly string[],
  ][]) {
    for (const seatId of seatIds) {
      stateBySeatId.set(seatId, state);
    }
  }

  const definedSeatIds = new Set(flattenSeats(seatMap).map((seat) => seat.id));

  for (const seatId of stateBySeatId.keys()) {
    if (!definedSeatIds.has(seatId)) {
      throw new Error(`Scenario references missing seat ${seatId}.`);
    }
  }

  return {
    ...seatMap,
    rows: seatMap.rows.map((row) => ({
      ...row,
      seats: row.seats.map((seat) => ({
        ...seat,
        state: stateBySeatId.get(seat.id) ?? seat.state,
      })),
    })),
  };
}
