import { PREMIUM_SEAT_PRICE, STANDARD_SEAT_PRICE } from "@/lib/constants";
import { seedMovies } from "@/seed/movies";
import { seedScreens } from "@/seed/screens";
import { seedShowtimes } from "@/seed/showtimes";
import type {
  Booking,
  BookingSeat,
  SeatStatus,
  Showtime,
} from "@/types/domain";

const now = "2026-04-27T00:00:00.000Z";

type SeedBookingInput = Omit<
  Booking,
  "movieId" | "movieTitle" | "showtimeStartsAt" | "seats" | "totalCost"
> & {
  seatKeys: string[];
};

function findShowtime(showtimeId: string) {
  const showtime = seedShowtimes.find(
    (candidate) => candidate.id === showtimeId
  );

  if (!showtime) {
    throw new Error(`Seed showtime ${showtimeId} was not found.`);
  }

  return showtime;
}

function findMovie(movieId: string) {
  const movie = seedMovies.find((candidate) => candidate.id === movieId);

  if (!movie) {
    throw new Error(`Seed movie ${movieId} was not found.`);
  }

  return movie;
}

function buildBookingSeats(screenId: string, seatKeys: string[]) {
  const screen = seedScreens.find((candidate) => candidate.id === screenId);

  if (!screen) {
    throw new Error(`Seed screen ${screenId} was not found.`);
  }

  return seatKeys.map<BookingSeat>((seatKey) => {
    const seat = screen.seats.find(
      (candidate) => `${candidate.rowLabel}${candidate.seatNumber}` === seatKey
    );

    if (!seat) {
      throw new Error(`Seed seat ${screenId}-${seatKey} was not found.`);
    }

    return {
      seatId: seat.id,
      rowLabel: seat.rowLabel,
      seatNumber: seat.seatNumber,
      seatType: seat.type,
      price: seat.type === "PREMIUM" ? PREMIUM_SEAT_PRICE : STANDARD_SEAT_PRICE,
    };
  });
}

function buildBooking(input: SeedBookingInput): Booking {
  const showtime = input.showtimeId ? findShowtime(input.showtimeId) : null;
  const movie = showtime ? findMovie(showtime.movieId) : null;
  const seats = buildBookingSeats(input.screenId, input.seatKeys);

  return {
    ...input,
    movieId: movie?.id,
    movieTitle: movie?.title,
    showtimeStartsAt: showtime?.startsAt,
    seats,
    totalCost: seats.reduce((total, seat) => total + seat.price, 0),
  };
}

export const seedBookings: Booking[] = [
  buildBooking({
    id: "booking-seed-adon-bilivit",
    showtimeId: "showtime-avatar-aang-main-20260502-0930",
    screenId: "screen-1",
    bookingReference: "TR-ADON-0930",
    customerName: "Adon Bilivit",
    customerEmail: "adon.bilivit@example.com",
    customerPhone: "+94 77 100 4101",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["D5", "D6"],
    holdExpiresAt: null,
    createdAt: "2026-04-27T07:20:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-justin-case",
    showtimeId: "showtime-parasite-studio-20260502-1230",
    screenId: "screen-3",
    bookingReference: "TR-JUSTIN-1230",
    customerName: "Justin Case",
    customerEmail: "justin.case@example.com",
    customerPhone: "+94 77 100 4102",
    status: "CONFIRMED",
    allocationMode: "MANUAL",
    seatKeys: ["C3", "C4"],
    holdExpiresAt: null,
    createdAt: "2026-04-27T08:05:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-anita-break",
    showtimeId: "showtime-ne-zha-2-grand-20260502-1830",
    screenId: "screen-2",
    bookingReference: "TR-ANITA-1830",
    customerName: "Anita Break",
    customerEmail: "anita.break@example.com",
    customerPhone: "+94 77 100 4103",
    status: "HELD",
    allocationMode: "AUTO",
    seatKeys: ["E6", "E7", "E8"],
    holdExpiresAt: "2026-05-02T12:40:00.000Z",
    createdAt: "2026-04-27T09:40:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-al-beback",
    showtimeId: "showtime-the-legend-of-hei-main-20260503-0930",
    screenId: "screen-1",
    bookingReference: "TR-AL-0930",
    customerName: "Al Beback",
    customerEmail: "al.beback@example.com",
    customerPhone: "+94 77 100 4104",
    status: "CONFIRMED",
    allocationMode: "MANUAL",
    seatKeys: ["E4", "E5", "E6", "E7"],
    holdExpiresAt: null,
    createdAt: "2026-04-27T11:10:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-iona-ticket",
    showtimeId: "showtime-flow-studio-20260503-1530",
    screenId: "screen-3",
    bookingReference: "TR-IONA-1530",
    customerName: "Iona Ticket",
    customerEmail: "iona.ticket@example.com",
    customerPhone: "+94 77 100 4105",
    status: "CANCELLED",
    allocationMode: "AUTO",
    seatKeys: ["B2", "B3"],
    holdExpiresAt: null,
    createdAt: "2026-04-27T12:25:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-paige-turner",
    showtimeId: "showtime-parasite-main-20260504-0930",
    screenId: "screen-1",
    bookingReference: "TR-PAIGE-0930",
    customerName: "Paige Turner",
    customerEmail: "paige.turner@example.com",
    customerPhone: "+94 77 100 4106",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["F4", "F5", "F6"],
    holdExpiresAt: null,
    createdAt: "2026-04-27T14:45:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-bea-rightback",
    showtimeId: "showtime-godzilla-minus-one-grand-20260504-1230",
    screenId: "screen-2",
    bookingReference: "TR-BEA-1230",
    customerName: "Bea Rightback",
    customerEmail: "bea.rightback@example.com",
    customerPhone: "+94 77 100 4107",
    status: "EXPIRED",
    allocationMode: "MANUAL",
    seatKeys: ["G5", "G6"],
    holdExpiresAt: "2026-04-27T12:30:00.000Z",
    createdAt: "2026-04-27T15:30:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-noah-lott",
    showtimeId: "showtime-avatar-aang-grand-20260504-1830",
    screenId: "screen-2",
    bookingReference: "TR-NOAH-1830",
    customerName: "Noah Lott",
    customerEmail: "noah.lott@example.com",
    customerPhone: "+94 77 100 4108",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["F5", "F6", "F7", "F8"],
    holdExpiresAt: null,
    createdAt: "2026-04-27T16:15:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-holly-day",
    showtimeId: "showtime-spider-verse-main-20260503-1830",
    screenId: "screen-1",
    bookingReference: "TR-HOLLY-1830",
    customerName: "Holly Day",
    customerEmail: "holly.day@example.com",
    customerPhone: "+94 77 100 4109",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["D4", "D5", "D6", "D7"],
    holdExpiresAt: null,
    createdAt: "2026-04-27T16:50:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-ella-vator",
    showtimeId: "showtime-ne-zha-2-main-20260504-1530",
    screenId: "screen-1",
    bookingReference: "TR-ELLA-1530",
    customerName: "Ella Vator",
    customerEmail: "ella.vator@example.com",
    customerPhone: "+94 77 100 4110",
    status: "HELD",
    allocationMode: "MANUAL",
    seatKeys: ["E4", "E5"],
    holdExpiresAt: "2026-05-04T09:40:00.000Z",
    createdAt: "2026-04-27T17:20:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-barry-cade",
    showtimeId: "showtime-avatar-aang-main-20260502-0930",
    screenId: "screen-1",
    bookingReference: "TR-BARRY-0930",
    customerName: "Barry Cade",
    customerEmail: "barry.cade@example.com",
    customerPhone: "+94 77 100 4111",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["F4", "F5", "F6", "F7", "F8"],
    holdExpiresAt: null,
    createdAt: "2026-04-27T17:55:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-clara-fication",
    showtimeId: "showtime-inside-out-2-grand-20260502-1530",
    screenId: "screen-2",
    bookingReference: "TR-CLARA-1530",
    customerName: "Clara Fication",
    customerEmail: "clara.fication@example.com",
    customerPhone: "+94 77 100 4112",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["E4", "E5", "E6", "E7", "E8", "E9"],
    holdExpiresAt: null,
    createdAt: "2026-04-27T18:25:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-max-capacity",
    showtimeId: "showtime-dune-part-two-grand-20260503-1230",
    screenId: "screen-2",
    bookingReference: "TR-MAX-1230",
    customerName: "Max Capacity",
    customerEmail: "max.capacity@example.com",
    customerPhone: "+94 77 100 4113",
    status: "CONFIRMED",
    allocationMode: "MANUAL",
    seatKeys: ["H4", "H5", "H6", "H7", "H8", "H9"],
    holdExpiresAt: null,
    createdAt: "2026-04-27T19:00:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-sue-perb",
    showtimeId: "showtime-godzilla-minus-one-grand-20260504-1230",
    screenId: "screen-2",
    bookingReference: "TR-SUE-1230",
    customerName: "Sue Perb",
    customerEmail: "sue.perb@example.com",
    customerPhone: "+94 77 100 4114",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["E4", "E5", "E6", "E7", "E8"],
    holdExpiresAt: null,
    createdAt: "2026-04-27T19:35:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-gene-erous",
    showtimeId: "showtime-avatar-aang-grand-20260504-1830",
    screenId: "screen-2",
    bookingReference: "TR-GENE-1830",
    customerName: "Gene Erous",
    customerEmail: "gene.erous@example.com",
    customerPhone: "+94 77 100 4115",
    status: "HELD",
    allocationMode: "MANUAL",
    seatKeys: ["G4", "G5", "G6"],
    holdExpiresAt: "2026-05-04T12:40:00.000Z",
    createdAt: "2026-04-27T20:05:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-nina-row",
    showtimeId: "showtime-ne-zha-2-grand-20260502-1830",
    screenId: "screen-2",
    bookingReference: "TR-NINA-1830",
    customerName: "Nina Row",
    customerEmail: "nina.row@example.com",
    customerPhone: "+94 77 100 4116",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["H4", "H5", "H6", "H7"],
    holdExpiresAt: null,
    createdAt: "2026-04-27T20:45:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-mona-lott",
    showtimeId: "showtime-parasite-studio-20260502-1230",
    screenId: "screen-3",
    bookingReference: "TR-MONA-1230",
    customerName: "Mona Lott",
    customerEmail: "mona.lott@example.com",
    customerPhone: "+94 77 100 4117",
    status: "CONFIRMED",
    allocationMode: "MANUAL",
    seatKeys: ["B2", "B3", "B4"],
    holdExpiresAt: null,
    createdAt: "2026-04-27T21:20:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-cam-era",
    showtimeId: "showtime-inside-out-2-grand-20260502-1530",
    screenId: "screen-2",
    bookingReference: "TR-CAM-1530",
    customerName: "Cam Era",
    customerEmail: "cam.era@example.com",
    customerPhone: "+94 77 100 4118",
    status: "CONFIRMED",
    allocationMode: "MANUAL",
    seatKeys: ["F4", "F5", "F6", "F7"],
    holdExpiresAt: null,
    createdAt: "2026-04-27T21:45:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-rhea-served",
    showtimeId: "showtime-inside-out-2-grand-20260502-1530",
    screenId: "screen-2",
    bookingReference: "TR-RHEA-1530",
    customerName: "Rhea Served",
    customerEmail: "rhea.served@example.com",
    customerPhone: "+94 77 100 4119",
    status: "HELD",
    allocationMode: "AUTO",
    seatKeys: ["G4", "G5", "G6"],
    holdExpiresAt: "2026-05-02T09:40:00.000Z",
    createdAt: "2026-04-27T22:05:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-tony-balcony",
    showtimeId: "showtime-dune-part-two-grand-20260503-1230",
    screenId: "screen-2",
    bookingReference: "TR-TONY-1230",
    customerName: "Tony Balcony",
    customerEmail: "tony.balcony@example.com",
    customerPhone: "+94 77 100 4120",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["E4", "E5", "E6", "E7", "E8"],
    holdExpiresAt: null,
    createdAt: "2026-04-27T22:30:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-lana-queue",
    showtimeId: "showtime-dune-part-two-grand-20260503-1230",
    screenId: "screen-2",
    bookingReference: "TR-LANA-1230",
    customerName: "Lana Queue",
    customerEmail: "lana.queue@example.com",
    customerPhone: "+94 77 100 4121",
    status: "CONFIRMED",
    allocationMode: "MANUAL",
    seatKeys: ["F8", "F9", "F10"],
    holdExpiresAt: null,
    createdAt: "2026-04-27T22:55:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-oscar-nite",
    showtimeId: "showtime-godzilla-minus-one-grand-20260504-1230",
    screenId: "screen-2",
    bookingReference: "TR-OSCAR-1230",
    customerName: "Oscar Nite",
    customerEmail: "oscar.nite@example.com",
    customerPhone: "+94 77 100 4122",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["F4", "F5", "F6", "F7"],
    holdExpiresAt: null,
    createdAt: "2026-04-27T23:15:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-penny-lane",
    showtimeId: "showtime-godzilla-minus-one-grand-20260504-1230",
    screenId: "screen-2",
    bookingReference: "TR-PENNY-1230",
    customerName: "Penny Lane",
    customerEmail: "penny.lane@example.com",
    customerPhone: "+94 77 100 4123",
    status: "HELD",
    allocationMode: "MANUAL",
    seatKeys: ["G7", "G8", "G9"],
    holdExpiresAt: "2026-05-04T06:40:00.000Z",
    createdAt: "2026-04-27T23:40:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-victor-view",
    showtimeId: "showtime-avatar-aang-grand-20260504-1830",
    screenId: "screen-2",
    bookingReference: "TR-VICTOR-1830",
    customerName: "Victor View",
    customerEmail: "victor.view@example.com",
    customerPhone: "+94 77 100 4124",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["E4", "E5", "E6", "E7"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T00:05:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-wendy-wide",
    showtimeId: "showtime-ne-zha-2-grand-20260502-1830",
    screenId: "screen-2",
    bookingReference: "TR-WENDY-1830",
    customerName: "Wendy Wide",
    customerEmail: "wendy.wide@example.com",
    customerPhone: "+94 77 100 4125",
    status: "CONFIRMED",
    allocationMode: "MANUAL",
    seatKeys: ["F4", "F5", "F6", "F7", "F8"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T00:30:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-dina-seat",
    showtimeId: "showtime-spider-verse-main-20260503-1830",
    screenId: "screen-1",
    bookingReference: "TR-DINA-1830",
    customerName: "Dina Seat",
    customerEmail: "dina.seat@example.com",
    customerPhone: "+94 77 100 4126",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["E4", "E5", "E6"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T00:55:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-eric-aisle",
    showtimeId: "showtime-spider-verse-main-20260503-1830",
    screenId: "screen-1",
    bookingReference: "TR-ERIC-1830",
    customerName: "Eric Aisle",
    customerEmail: "eric.aisle@example.com",
    customerPhone: "+94 77 100 4127",
    status: "HELD",
    allocationMode: "MANUAL",
    seatKeys: ["F4", "F5"],
    holdExpiresAt: "2026-05-03T12:40:00.000Z",
    createdAt: "2026-04-28T01:20:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-faye-mous",
    showtimeId: "showtime-ne-zha-2-main-20260504-1530",
    screenId: "screen-1",
    bookingReference: "TR-FAYE-1530",
    customerName: "Faye Mous",
    customerEmail: "faye.mous@example.com",
    customerPhone: "+94 77 100 4128",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["D4", "D5", "D6", "D7"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T01:45:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-gary-front",
    showtimeId: "showtime-the-legend-of-hei-main-20260503-0930",
    screenId: "screen-1",
    bookingReference: "TR-GARY-0930",
    customerName: "Gary Front",
    customerEmail: "gary.front@example.com",
    customerPhone: "+94 77 100 4129",
    status: "CONFIRMED",
    allocationMode: "MANUAL",
    seatKeys: ["D4", "D5", "D6"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T02:10:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-ivy-center",
    showtimeId: "showtime-parasite-main-20260504-0930",
    screenId: "screen-1",
    bookingReference: "TR-IVY-0930",
    customerName: "Ivy Center",
    customerEmail: "ivy.center@example.com",
    customerPhone: "+94 77 100 4130",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["D4", "D5"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T02:35:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-kara-corner",
    showtimeId: "showtime-flow-studio-20260503-1530",
    screenId: "screen-3",
    bookingReference: "TR-KARA-1530",
    customerName: "Kara Corner",
    customerEmail: "kara.corner@example.com",
    customerPhone: "+94 77 100 4131",
    status: "CONFIRMED",
    allocationMode: "MANUAL",
    seatKeys: ["C3", "C4"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T03:00:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-lee-light",
    showtimeId: "showtime-parasite-studio-20260502-1230",
    screenId: "screen-3",
    bookingReference: "TR-LEE-1230",
    customerName: "Lee Light",
    customerEmail: "lee.light@example.com",
    customerPhone: "+94 77 100 4132",
    status: "HELD",
    allocationMode: "AUTO",
    seatKeys: ["D4", "D5"],
    holdExpiresAt: "2026-05-02T06:40:00.000Z",
    createdAt: "2026-04-28T03:25:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-rita-row",
    showtimeId: "showtime-inside-out-2-grand-20260502-1530",
    screenId: "screen-2",
    bookingReference: "TR-RITA-1530",
    customerName: "Rita Row",
    customerEmail: "rita.row@example.com",
    customerPhone: "+94 77 100 4133",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["D5", "D6", "D7", "D8"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T03:50:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-sam-screen",
    showtimeId: "showtime-inside-out-2-grand-20260502-1530",
    screenId: "screen-2",
    bookingReference: "TR-SAM-1530",
    customerName: "Sam Screen",
    customerEmail: "sam.screen@example.com",
    customerPhone: "+94 77 100 4134",
    status: "CONFIRMED",
    allocationMode: "MANUAL",
    seatKeys: ["H4", "H5", "H6", "H7"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T04:15:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-tara-tier",
    showtimeId: "showtime-inside-out-2-grand-20260502-1530",
    screenId: "screen-2",
    bookingReference: "TR-TARA-1530",
    customerName: "Tara Tier",
    customerEmail: "tara.tier@example.com",
    customerPhone: "+94 77 100 4135",
    status: "HELD",
    allocationMode: "AUTO",
    seatKeys: ["I5", "I6", "I7"],
    holdExpiresAt: "2026-05-02T09:40:00.000Z",
    createdAt: "2026-04-28T04:40:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-val-view",
    showtimeId: "showtime-dune-part-two-grand-20260503-1230",
    screenId: "screen-2",
    bookingReference: "TR-VAL-1230",
    customerName: "Val View",
    customerEmail: "val.view@example.com",
    customerPhone: "+94 77 100 4137",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["G4", "G5", "G6", "G7", "G8"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T05:30:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-walt-wide",
    showtimeId: "showtime-dune-part-two-grand-20260503-1230",
    screenId: "screen-2",
    bookingReference: "TR-WALT-1230",
    customerName: "Walt Wide",
    customerEmail: "walt.wide@example.com",
    customerPhone: "+94 77 100 4138",
    status: "CONFIRMED",
    allocationMode: "MANUAL",
    seatKeys: ["I4", "I5", "I6", "I7"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T05:55:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-xena-zone",
    showtimeId: "showtime-dune-part-two-grand-20260503-1230",
    screenId: "screen-2",
    bookingReference: "TR-XENA-1230",
    customerName: "Xena Zone",
    customerEmail: "xena.zone@example.com",
    customerPhone: "+94 77 100 4139",
    status: "HELD",
    allocationMode: "AUTO",
    seatKeys: ["D6", "D7", "D8", "D9"],
    holdExpiresAt: "2026-05-03T06:40:00.000Z",
    createdAt: "2026-04-28T06:20:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-yara-balcony",
    showtimeId: "showtime-dune-part-two-grand-20260503-1230",
    screenId: "screen-2",
    bookingReference: "TR-YARA-1230",
    customerName: "Yara Balcony",
    customerEmail: "yara.balcony@example.com",
    customerPhone: "+94 77 100 4140",
    status: "CONFIRMED",
    allocationMode: "MANUAL",
    seatKeys: ["C5", "C6", "C7"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T06:45:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-zane-center",
    showtimeId: "showtime-godzilla-minus-one-grand-20260504-1230",
    screenId: "screen-2",
    bookingReference: "TR-ZANE-1230",
    customerName: "Zane Center",
    customerEmail: "zane.center@example.com",
    customerPhone: "+94 77 100 4141",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["H4", "H5", "H6", "H7", "H8"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T07:10:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-amy-aisle",
    showtimeId: "showtime-godzilla-minus-one-grand-20260504-1230",
    screenId: "screen-2",
    bookingReference: "TR-AMY-1230",
    customerName: "Amy Aisle",
    customerEmail: "amy.aisle@example.com",
    customerPhone: "+94 77 100 4142",
    status: "CONFIRMED",
    allocationMode: "MANUAL",
    seatKeys: ["I4", "I5", "I6"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T07:35:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-bryce-backrow",
    showtimeId: "showtime-godzilla-minus-one-grand-20260504-1230",
    screenId: "screen-2",
    bookingReference: "TR-BRYCE-1230",
    customerName: "Bryce Backrow",
    customerEmail: "bryce.backrow@example.com",
    customerPhone: "+94 77 100 4143",
    status: "HELD",
    allocationMode: "AUTO",
    seatKeys: ["D5", "D6", "D7", "D8"],
    holdExpiresAt: "2026-05-04T06:40:00.000Z",
    createdAt: "2026-04-28T08:00:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-cora-circle",
    showtimeId: "showtime-avatar-aang-grand-20260504-1830",
    screenId: "screen-2",
    bookingReference: "TR-CORA-1830",
    customerName: "Cora Circle",
    customerEmail: "cora.circle@example.com",
    customerPhone: "+94 77 100 4144",
    status: "CONFIRMED",
    allocationMode: "MANUAL",
    seatKeys: ["H4", "H5", "H6", "H7", "H8"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T08:25:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-drew-deck",
    showtimeId: "showtime-avatar-aang-grand-20260504-1830",
    screenId: "screen-2",
    bookingReference: "TR-DREW-1830",
    customerName: "Drew Deck",
    customerEmail: "drew.deck@example.com",
    customerPhone: "+94 77 100 4145",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["I5", "I6", "I7", "I8"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T08:50:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-emma-edge",
    showtimeId: "showtime-avatar-aang-grand-20260504-1830",
    screenId: "screen-2",
    bookingReference: "TR-EMMA-1830",
    customerName: "Emma Edge",
    customerEmail: "emma.edge@example.com",
    customerPhone: "+94 77 100 4146",
    status: "HELD",
    allocationMode: "MANUAL",
    seatKeys: ["D5", "D6", "D7"],
    holdExpiresAt: "2026-05-04T12:40:00.000Z",
    createdAt: "2026-04-28T09:15:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-finn-floor",
    showtimeId: "showtime-ne-zha-2-grand-20260502-1830",
    screenId: "screen-2",
    bookingReference: "TR-FINN-1830",
    customerName: "Finn Floor",
    customerEmail: "finn.floor@example.com",
    customerPhone: "+94 77 100 4147",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["G4", "G5", "G6", "G7", "G8"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T09:40:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-gina-gallery",
    showtimeId: "showtime-ne-zha-2-grand-20260502-1830",
    screenId: "screen-2",
    bookingReference: "TR-GINA-1830",
    customerName: "Gina Gallery",
    customerEmail: "gina.gallery@example.com",
    customerPhone: "+94 77 100 4148",
    status: "CONFIRMED",
    allocationMode: "MANUAL",
    seatKeys: ["E9", "E10", "E11"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T10:05:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-hugo-house",
    showtimeId: "showtime-ne-zha-2-grand-20260502-1830",
    screenId: "screen-2",
    bookingReference: "TR-HUGO-1830",
    customerName: "Hugo House",
    customerEmail: "hugo.house@example.com",
    customerPhone: "+94 77 100 4149",
    status: "HELD",
    allocationMode: "AUTO",
    seatKeys: ["I4", "I5", "I6", "I7"],
    holdExpiresAt: "2026-05-02T12:40:00.000Z",
    createdAt: "2026-04-28T10:30:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-iris-isle",
    showtimeId: "showtime-ne-zha-2-grand-20260502-1830",
    screenId: "screen-2",
    bookingReference: "TR-IRIS-1830",
    customerName: "Iris Isle",
    customerEmail: "iris.isle@example.com",
    customerPhone: "+94 77 100 4150",
    status: "CONFIRMED",
    allocationMode: "MANUAL",
    seatKeys: ["D5", "D6"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T10:55:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-jules-main",
    showtimeId: "showtime-avatar-aang-main-20260502-0930",
    screenId: "screen-1",
    bookingReference: "TR-JULES-0930",
    customerName: "Jules Main",
    customerEmail: "jules.main@example.com",
    customerPhone: "+94 77 100 4151",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["C4", "C5", "C6", "C7"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T11:20:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-kim-middle",
    showtimeId: "showtime-avatar-aang-main-20260502-0930",
    screenId: "screen-1",
    bookingReference: "TR-KIM-0930",
    customerName: "Kim Middle",
    customerEmail: "kim.middle@example.com",
    customerPhone: "+94 77 100 4152",
    status: "CONFIRMED",
    allocationMode: "MANUAL",
    seatKeys: ["E4", "E5", "E6", "E7"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T11:45:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-luke-lobby",
    showtimeId: "showtime-avatar-aang-main-20260502-0930",
    screenId: "screen-1",
    bookingReference: "TR-LUKE-0930",
    customerName: "Luke Lobby",
    customerEmail: "luke.lobby@example.com",
    customerPhone: "+94 77 100 4153",
    status: "HELD",
    allocationMode: "AUTO",
    seatKeys: ["G4", "G5", "G6"],
    holdExpiresAt: "2026-05-02T03:40:00.000Z",
    createdAt: "2026-04-28T12:10:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-mia-matinee",
    showtimeId: "showtime-avatar-aang-main-20260502-0930",
    screenId: "screen-1",
    bookingReference: "TR-MIA-0930",
    customerName: "Mia Matinee",
    customerEmail: "mia.matinee@example.com",
    customerPhone: "+94 77 100 4154",
    status: "CONFIRMED",
    allocationMode: "MANUAL",
    seatKeys: ["B5", "B6"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T12:35:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-nora-night",
    showtimeId: "showtime-spider-verse-main-20260503-1830",
    screenId: "screen-1",
    bookingReference: "TR-NORA-1830",
    customerName: "Nora Night",
    customerEmail: "nora.night@example.com",
    customerPhone: "+94 77 100 4155",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["G4", "G5", "G6", "G7"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T13:00:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-owen-orchestra",
    showtimeId: "showtime-spider-verse-main-20260503-1830",
    screenId: "screen-1",
    bookingReference: "TR-OWEN-1830",
    customerName: "Owen Orchestra",
    customerEmail: "owen.orchestra@example.com",
    customerPhone: "+94 77 100 4156",
    status: "CONFIRMED",
    allocationMode: "MANUAL",
    seatKeys: ["C4", "C5", "C6"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T13:25:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-pia-premium",
    showtimeId: "showtime-spider-verse-main-20260503-1830",
    screenId: "screen-1",
    bookingReference: "TR-PIA-1830",
    customerName: "Pia Premium",
    customerEmail: "pia.premium@example.com",
    customerPhone: "+94 77 100 4157",
    status: "HELD",
    allocationMode: "AUTO",
    seatKeys: ["E7", "E8"],
    holdExpiresAt: "2026-05-03T12:40:00.000Z",
    createdAt: "2026-04-28T13:50:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-quinn-queue",
    showtimeId: "showtime-ne-zha-2-main-20260504-1530",
    screenId: "screen-1",
    bookingReference: "TR-QUINN-1530",
    customerName: "Quinn Queue",
    customerEmail: "quinn.queue@example.com",
    customerPhone: "+94 77 100 4158",
    status: "CONFIRMED",
    allocationMode: "MANUAL",
    seatKeys: ["F4", "F5", "F6", "F7"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T14:15:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-rose-reserve",
    showtimeId: "showtime-the-legend-of-hei-main-20260503-0930",
    screenId: "screen-1",
    bookingReference: "TR-ROSE-0930",
    customerName: "Rose Reserve",
    customerEmail: "rose.reserve@example.com",
    customerPhone: "+94 77 100 4159",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["F4", "F5", "F6", "F7"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T14:40:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-seth-stage",
    showtimeId: "showtime-the-legend-of-hei-main-20260503-0930",
    screenId: "screen-1",
    bookingReference: "TR-SETH-0930",
    customerName: "Seth Stage",
    customerEmail: "seth.stage@example.com",
    customerPhone: "+94 77 100 4160",
    status: "CONFIRMED",
    allocationMode: "MANUAL",
    seatKeys: ["C5", "C6", "C7"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T15:05:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-tess-ticket",
    showtimeId: "showtime-parasite-main-20260504-0930",
    screenId: "screen-1",
    bookingReference: "TR-TESS-0930",
    customerName: "Tess Ticket",
    customerEmail: "tess.ticket@example.com",
    customerPhone: "+94 77 100 4161",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["E4", "E5", "E6", "E7"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T15:30:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-una-studio",
    showtimeId: "showtime-parasite-studio-20260502-1230",
    screenId: "screen-3",
    bookingReference: "TR-UNA-1230",
    customerName: "Una Studio",
    customerEmail: "una.studio@example.com",
    customerPhone: "+94 77 100 4162",
    status: "CONFIRMED",
    allocationMode: "MANUAL",
    seatKeys: ["A2", "A3", "A4"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T15:55:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-vera-venue",
    showtimeId: "showtime-parasite-studio-20260502-1230",
    screenId: "screen-3",
    bookingReference: "TR-VERA-1230",
    customerName: "Vera Venue",
    customerEmail: "vera.venue@example.com",
    customerPhone: "+94 77 100 4163",
    status: "CONFIRMED",
    allocationMode: "AUTO",
    seatKeys: ["E2", "E3", "E4"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T16:20:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-wade-window",
    showtimeId: "showtime-flow-studio-20260503-1530",
    screenId: "screen-3",
    bookingReference: "TR-WADE-1530",
    customerName: "Wade Window",
    customerEmail: "wade.window@example.com",
    customerPhone: "+94 77 100 4164",
    status: "CONFIRMED",
    allocationMode: "MANUAL",
    seatKeys: ["B4", "B5", "B6"],
    holdExpiresAt: null,
    createdAt: "2026-04-28T16:45:00.000Z",
    updatedAt: now,
  }),
  buildBooking({
    id: "booking-seed-zara-zoom",
    showtimeId: "showtime-flow-studio-20260503-1530",
    screenId: "screen-3",
    bookingReference: "TR-ZARA-1530",
    customerName: "Zara Zoom",
    customerEmail: "zara.zoom@example.com",
    customerPhone: "+94 77 100 4165",
    status: "HELD",
    allocationMode: "AUTO",
    seatKeys: ["A3", "A4"],
    holdExpiresAt: "2026-05-03T09:40:00.000Z",
    createdAt: "2026-04-28T17:10:00.000Z",
    updatedAt: now,
  }),
];

function seatStatusForBooking(booking: Booking): SeatStatus | null {
  if (booking.status === "CONFIRMED") {
    return "BOOKED";
  }

  if (booking.status === "HELD") {
    return "HELD";
  }

  return null;
}

export function applySeedBookingsToShowtimes(showtimes: Showtime[]) {
  const bookingSeatStates = new Map<
    string,
    Map<string, { status: SeatStatus; heldByBookingId: string | null }>
  >();

  for (const booking of seedBookings) {
    if (!booking.showtimeId) {
      continue;
    }

    const status = seatStatusForBooking(booking);

    if (!status) {
      continue;
    }

    const statesForShowtime =
      bookingSeatStates.get(booking.showtimeId) ?? new Map();

    for (const seat of booking.seats) {
      statesForShowtime.set(seat.seatId, {
        status,
        heldByBookingId: status === "HELD" ? booking.id : null,
      });
    }

    bookingSeatStates.set(booking.showtimeId, statesForShowtime);
  }

  return showtimes.map<Showtime>((showtime) => {
    const statesForShowtime = bookingSeatStates.get(showtime.id);

    if (!statesForShowtime) {
      return showtime;
    }

    return {
      ...showtime,
      seatStates: showtime.seatStates.map((seatState) => {
        const bookedState = statesForShowtime.get(seatState.seatId);

        return bookedState ? { ...seatState, ...bookedState } : seatState;
      }),
    };
  });
}
